name: Build My First Game
on: push

jobs:
  build:
    name: ${{ matrix.platform.name }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: 'Linux (x64)'   ,os: ubuntu-22.04              }
          - { name: 'Windows (x64)' ,os: windows-2022              }
          - { name: 'Mac (x64)'     ,os: macos-12                  }
          - { name: 'Mac (arm64)'   ,os: macos-12     ,arch: arm64 }

    runs-on: ${{ matrix.platform.os }}

    steps:
      - uses: actions/checkout@v3

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROSS_COMPILE_ARCH: ${{ matrix.platform.arch }}
        run: |
          make main
          mv "main" "MyFirstGame"

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform.os }}
          path: MyFirstGame
