name: Create Release Draft
on:
  workflow_run:
    workflows: [ "Build My First Game" ]
    branches: [ master ]
    types:
      - completed
jobs:
  draft:
    runs-on: ubuntu-latest
    env:
      GH_REPO: ${{ github.repository }}
    steps:
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.27.0
        with:
          branch: master
          workflow: build.yaml
          path: download
          workflow_conclusion: success
      - run: |
          tree
          mkdir dist
          # Extract MyFirstGame from Linux (x64)
          cp download/"Linux (x64)"/MyFirstGame dist/
          # Extract MyFirstGame from Mac (arm64)
          cp download/"Mac (arm64)"/MyFirstGame dist/
          # Extract MyFirstGame from Mac (x64)
          cp download/"Mac (x64)"/MyFirstGame dist/
          # Extract MyFirstGame.exe from Windows (x64)/Release
          cp download/"Windows (x64)"/Release/MyFirstGame.exe dist/

      - name: Create Release Draft
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create new --draft dist/**